name: CI Teste HTML/CSS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: Verificar arquivos existentes
        run: |
          echo "Verificando arquivos..."
          test -f index.html && echo "index.html encontrado âœ…"
          test -f style.css && echo "style.css encontrado âœ…"

      - name: Teste final
        run: echo "Pipeline concluÃ­do com sucesso! ðŸš€"


      - name: Teste SAST
        run: echo "Executando teste SAST"

      - name: Teste DAST
        run: echo "Executando teste DAST"
